events {}

http {
  server {
    listen 443 ssl;
    server_name schoolsafetrack.work.gd www.schoolsafetrack.work.gd;

    ssl_certificate     /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    # Frontend
    location / {
      proxy_pass http://frontend:5173;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # Backend
    location /api/ {
      proxy_pass http://backend:3000/api/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }
  }
}
